### ISSUE TITLE
Fix rust audit report error

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/stargate#15]
https://circleci.com/gh/starcoinorg/stargate/51

ID:       RUSTSEC-2019-0004
Crate:    libp2p-core
Version:  0.7.0
Date:     2019-05-15
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0004
Title:    Failure to properly verify ed25519 signatures makes any signature valid
Solution:  upgrade to ^0.7.1 OR >= 0.8.1
Dependency tree: 
libp2p-core 0.7.0

**Comment by fikgol** [comment]
Already fixed. close it.
